### ISSUE TITLE
AttributeError: 'MyIOThermostate' object has no attribute '_unit_of_measurement'

### ISSUE THREAD

**Issue by tmsblgh** [akitaylor/homeassistant-myio#2]
2024-03-11 23:00:18.852 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Entity.async_write_ha_state()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 992, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1045, in __async_calculate_state
    capability_attr = self.capability_attributes
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 322, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 430, in capability_attributes
    temperature_unit = self.temperature_unit
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 322, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myio/climate.py", line 213, in temperature_unit
    return self._unit_of_measurement
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 322, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MyIOThermostate' object has no attribute '_unit_of_measurement'. Did you mean: 'unit_of_measurement'?

**Comment by akitaylor** [comment]
"Did you mean: 'unit_of_measurement'?" - surely not. The sensor variable gets a value in your case that is not handled. I updated the logging to identify the variable value.

**Comment by akitaylor** [comment]
the library is updated to home assistant 2025 using UnitOfTemparature enumeration.
